config/routes.rb
Knight::Application.routes.draw do

  # feedback.de / www.feedback.de -> institutions#index
  #   -> Marketing & List of all Universities I signed up
  #
  # uni-bamberg.feedback.de / uni-koeln.feedback.de -> channels#index
  #   --> University Homepage & List of all Channels to send a message to
  #
  # uni-bamberg.feedback.de/ivens -> channels#new_message
  #   --> Send a message to channel ivens at the uni-bamberg institution
  #
  # uni-bamberg.feedback.de/ivens/show
  #   --> Show the messages that are being sent to this channel in real-time
  #        & make existing messages available 

  # Channels
  # REVIEW: better subdomain constraints
  constraints subdomain: /uni-bamberg|uni-koeln|uni-augsburg/ do
    match '/'       => 'channels#index',            as: :channels
    get ':id'       => 'channels#new_message',      as: :new_message
    post ':id'      => 'channels#create_message',   as: :create_message
    get ':id/show'  => 'channels#show',             as: :channel
  end

  # Static Pages via Thoughtbot's High Voltage
  match ':id' => 'pages#show', as: :static, via: :get

  # Institutions
  # root_url and institutions_url both work
  match '/' => 'institutions#index', as: :institutions
  root to: 'institutions#index'

  # Link to your Static Pages
  #   anywhere in tue views using the link_to helper
  #   = link_to 'About', page_path(id: 'about')

  # See how all your routes lay out with 'rake routes'
end

app/models/channel.rb
# == Schema Information
#
# Table name: channels
#
#  created_at     :datetime         not null
#  description    :text
#  full_name      :string(255)
#  id             :integer          not null, primary key
#  institution_id :integer
#  name           :string(255)
#  slug           :string(255)
#  updated_at     :datetime         not null
#

class Channel < ActiveRecord::Base
    
  # A Channel belongs to an Institution
  #   and has many messages

  # Channel:
  #   name: Base for FriendlyId slug
  #   slug: Slugged name
  #   full_name: Full, human readable name
  #   description: Channel specific info

  # Relations
  belongs_to :institution
  has_many :messages, dependent: :destroy

  # ID
  extend FriendlyId
  friendly_id :name, use: [:slugged, :scoped], scope: :institution

  # Validations
  validates :name, uniqueness: { scope: :institution_id }

  # Whitelist
  attr_accessible :name, :full_name, :description

end

app/models/institution.rb
# == Schema Information
#
# Table name: institutions
#
#  created_at  :datetime         not null
#  description :text
#  full_name   :string(255)
#  id          :integer          not null, primary key
#  name        :string(255)
#  updated_at  :datetime         not null
#

class Institution < ActiveRecord::Base

  # An Institution can hold many channels

  # Institution:
  #   name: Subdomain, base for FriendlyId scopes
  #   full_name: Full, human readable Name
  #   description: Institution-specific text

  # Relations
  has_many :channels

  # FriendlyId
  extend FriendlyId
  friendly_id :name

  # Validations
  validates :name, uniqueness: true

  # Protect all attributes
  attr_accessible :description
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  channel_id :integer
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  message    :string(255)
#  name       :string(255)
#  updated_at :datetime         not null
#

class Message < ActiveRecord::Base

  # A message belongs to a Channel
  #  which in turn belongs to an Institution

  # Message:
  #  message: The message body
  #  name: Name of the Sender (optional)

  # Associations
  belongs_to :channel

  # Whitelist
  attr_accessible :message, :name

  # Validations
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  before_filter :load_institution, only: :index
  before_filter :load_channel, except: [:institution_index, :index]

  def index
    @channels = @institution.channels
  end

  def show
    @messages = @channel.messages
  end

  def new_message
    @message = @channel.messages.new
  end

  def create_message
    @message = @channel.messages.new(params[:message])
    if @message.save
      flash[:notice] = "Ihre Nachricht wurde erfolgreich gesendet. Vielen Dank!"
      html_message = render_to_string(partial: 'shared/message', locals: {message: @message})
      Pusher[@channel.name].trigger('new_message', html_message)
      redirect_to action: :new_message
    else
      flash.now.notice = "Bitte geben Sie eine Nachricht ein."
      render action: :new_message
    end
  end

protected

  def load_institution
    @institution = Institution.find(request.subdomain) unless request.subdomain == 'www'
  end

  def load_channel
    load_institution
    @channel = @institution.channels.find(params[:id])
  end

end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController

  def index
    @institutions = Institution.all  
  end

end

app/controllers/pages_controller.rb
class PagesController < HighVoltage::PagesController

  layout :layout_for_page

protected
  
  def layout_for_page
    # Requested Page is specified in params[:id]
    case params[:id]
    when 'readmejs'
      false
    else
      'application'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Flash Messages Container Classes
  def flash_message_container(type)
    klass = 'alert-box'
    klass = 'alert-box'         if type == :notice
    klass = 'alert-box success' if type == :success
    klass = 'alert-box'         if type == :alert
    klass = 'alert-box alert'   if type == :error
    klass
  end

  def error_class(obj, attribute)
    obj.errors[attribute].present? ? 'error': ''
  end

  def error_field(obj, attribute)
    obj.errors[attribute].present? ? "<small>#{ obj.errors.full_messages.join(', ') }</small>".html_safe : ""
  end

end

app/helpers/channel_helper.rb
module ChannelHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  # This might be a good place 
  #   for your View Helper Methods

end

app/views/application/_flash_messages.html.slim
/ flash_messages.html.slim

/ flash messages
- if flash
  - flash.each do |type, message|
    div class=flash_message_container(type)
      span = message
      a href='' class='close' &times;

app/views/application/_footer.html.slim
/ footer.html.slim

app/views/application/_javascripts_body.html.slim
/ javascripts_body.html.slim

/ Slim Filters
/   javascript:
/   coffee:
/   markdown:

/ javascripts in body
= javascript_include_tag 'application_body'

/ google analytics
- if Rails.env.production?
  javascript:
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'PLEASE_ENTER_YOUR_ACCOUNT_ID_HERE']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();


/ livereload (in development)
- if Rails.env.development?
    javascript:
      document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')

app/views/application/_topbar.html.slim
/ topbar.html.slim

/ home
/ if user is on channels#index direct him to root_utl, else redirect him to channels_path
- link_target = (params[:controller].to_sym == :channels && params[:action].to_sym == :index) ? root_url(subdomain: false) : channels_path
/ .right = link_to 'Home', link_target, class: 'button radius secondary'

/ institution name or feedback slogan
-  if @institution
  b = @institution.full_name
- else
  b 
    ' Wie können Sie Ihren Studenten helfen? 
    = link_to 'Mehr erfahren &raquo;'.html_safe, static_path(id: :features)


/ happy day
/ b.happyday
  /! Heavily influenced and inspired by 37signals. Thanks guys for your great work!
  coffee:
    dayNames = new Array("Sunday","Monday","Tuesday","Wednesday", "Thursday","Friday","Saturday")
    now = new Date()
    document.write("Happy " + dayNames[now.getDay()] + ".")

app/views/channel/index.html.slim
h1 Channel#index
p Find me in app/views/channel/index.html.slim

app/views/channel/new_message.html.slim
h1 Channel#new_message
p Find me in app/views/channel/new_message.html.slim

app/views/channel/show.html.slim
h1 Channel#show
p Find me in app/views/channel/show.html.slim

app/views/channels/index.html.slim
/ channels/index.html.slim

/ Institution
= render 'institutions/institution_header'

h5 Liebe Studenten!

p Über Feedback können Professoren live Ihre Stimme empfangen. Sagen Sie Ihnen, wo der Schuh drückt, und unsere Lehre wird auch in Zukunft immer besser werden.

.panel
  p Diese Professoren an der #{ @institution.full_name } <br /> freuen sich über Ihr Feedback:

  / Channels Listing
  ul.disc
    - @channels.each do |c|
      // Channel
      - display_name = c.full_name || c.name
      li.channel
        = link_to display_name, new_message_path(c)

app/views/channels/new_message.html.slim
/ new_message.html.slim

/ Institution
= render 'institutions/institution_header'

p: b Ihre Nachricht an #{ @channel.full_name }:

/ New Message Form
= form_for @message, url: create_message_path(@channel)  do |f|

  / Message
  = f.label :message, 'Nachricht <abbr title="benötigt">*</abbr>'.html_safe
  = f.text_area :message, style: 'height: 10rem;', autofocus: true, autocomplete: :off

  / Name
  = f.label :name, 'Ihr Name'
  = f.text_field :name, autocomplete: :off

  / Submit
  = f.button 'Senden', class: 'button radius', style: 'margin-right: 1rem'
  ' oder
  = link_to "zurück", channels_path

app/views/channels/show.html.slim
/ channel/show.html.slim

/ Institution
= render 'institutions/institution_header'

h6 Nachrichten an #{ @channel.full_name }

/ Messages
#messages
  = render partial: 'shared/message', collection: @messages

/ No live data yet
p.no_live_data_yet: em Bisher keine neuen Nachrichten eingegangen.

/ Show existing messages
p: b = link_to 'Alle Nachrichten anzeigen', '', class: 'show_existing_messages'

/ Send new message
/ p: b = link_to 'Neue Nachricht', new_message_path(@channel)

/ Pusher Integration
javascript:

  // Initialize
  var pusher = new Pusher('38bf35a8c429326ad783');
  var channel = pusher.subscribe('#{ @channel.name }');

  // Bind Events
  channel.bind('new_message', function(data) {
    $('.no_live_data_yet').hide();
    $('#messages').prepend(data).slideDown();
    // Highlight Message + Fade Highlighting Color Away
    $('#messages').children('.message').first().css({'background-color': '#ffff99'}).animate({'background-color': '#fff'}, 120000);
  });

  // Hide existing messages on load
  $('.message').hide();

  // Show all existing messages
  $('.show_existing_messages').click(function(e){
    e.preventDefault();
    $('.message').show();
    $('.no_live_data_yet').hide();
    $(this).hide();
  });

app/views/institutions/_institution_header.html.slim
/ _institution_header.html.slim

/ Institution
= link_to root_url(subdomain: @institution.name), class: 'institution' do
  .panel
    = image_tag("i/#{ @institution.name }/logo.png", style: 'max-height: 100px; max-width: 100px; vertical-align: middle', class: 'logo')
    b.name = @institution.full_name || @institution.name

app/views/institutions/index.html.slim
h2 Feedback
h4.subheader Die einfachste Art, im vollen Hörsaal <br> Fragen zu klären.

p Mit Feedback wird es für Sie als Dozenten einfach, immer zu wissen, was Ihre Studenten gerade verstehen und wo sie gerne nachfragen würden.

p = link_to 'Mehr erfahren &raquo;'.html_safe, static_path(id: :features), class: 'radius button'  

p Diese renommierte Hochschulen nutzen Feedback bereits um ihre Lehre noch weiter zu verbessern:

- @institutions.each do |i|
  = link_to root_url(subdomain: i.name), class: 'institution' do
    .panel
      = image_tag("i/#{ i.name }/logo.png", style: 'max-height: 100px; max-width: 100px; vertical-align: middle', class: 'logo')
      b.name = i.full_name || i.name

app/views/layouts/_body.html.slim
/ body.html.slim

/ topbar
#topbar.container
  .row
    .twelve.columns

      = render 'topbar'


/ main and sidebar
#main.row

  / Content
  #content.six.columns

    / flash messages
    = render 'flash_messages'

    / main body
    = yield


/ footer
#footer.row
  .twelve.columns

    = render 'footer'


/ javascripts in body
= render 'javascripts_body'

app/views/layouts/_head.html.slim
/ head.html.slim

/ Charset
meta charset='utf-8'

/ DNS Prefetch
/   (via http://html5boilerplate.com/docs/DNS-Prefetching/)
/   Google CDN (jQuery)
link rel="dns-prefetch" href="//ajax.googleapis.com"
/   Google Analytics
link rel="dns-prefetch" href="//www.google-analytics.com"
link rel="dns-prefetch" href="//google-analytics.com"
/   Github
link rel="dns-prefetch" href="//github.com"
link rel="dns-prefetch" href="https://github.com"
/   Twitter
link rel="dns-prefetch" href="https://twitter.com"


/ title and description
title StartingPoint
'
meta name='description' content='The very next major Web Startup you definitely should know about.'
meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'
meta name='viewport' content='width=device-width'

/ stylesheets
= stylesheet_link_tag 'application'

/ javascripts in head
/   jquery in body
= javascript_include_tag 'application_head'

/ jquery
= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'

/ pusher
= javascript_include_tag 'http://js.pusher.com/1.12/pusher.min.js'

/ csrf meta tags
= csrf_meta_tags

app/views/layouts/application.html.slim
/ layout: application.html.slim

doctype 5
html lang='en'

  / head
  head
    = render 'layouts/head'

  / body
  body class=controller_name
    = render 'layouts/body'

app/views/pages/features.html.slim
/ features.html.slim

h3 Feedback Features

app/views/pages/imprint.html.slim
/ imprint.html.slim

h1 Imprint

app/views/shared/_message.html.slim
/ message.html.slim

.message
  div.text: b = message.message
  span.name #{ message.name.present? ? message.name : '<em>Student/in</em>'.html_safe }
  span.time.right #{distance_of_time_in_words_to_now(message.updated_at)}